### ISSUE TITLE
Supported versions of IJ

### ISSUE THREAD

**Issue by AlexPl292** [Mishkun/ideavim-sneak#1]
For now, the plugin supports 2020.1.* versions of IJ. Is it possible include the 2020.2.* and 2020.3.* versions of IJ as well, or there are some incompatibilities? Special thanks if it would be possible to leave an empty "until-version", so the plugin could also be used from IJ nightly builds.

![image](https://user-images.githubusercontent.com/4203721/98810471-5bac9800-2430-11eb-8da7-aea85f0d9236.png)

**Comment by Mishkun** [comment]
@AlexPl292 Thanks for your feedback! Added `sameSinceUntilBuild` build property to intelij gradle plugin config. Hope this would help
