### ISSUE TITLE
How to bind only on normal mode or bind custom keys?

### ISSUE THREAD

**Issue by qwIvan** [Mishkun/ideavim-sneak#14]

**Comment by qwIvan** [comment]
Because it is conflict with `set surround` when `S` be invoked on visual mode.

**Comment by Mishkun** [comment]
Hi @qwIvan! You can try to swap `set surround` and `set sneak` instructions in your `~/.ideavimrc` file. Alternatively you can map your surround plugin action back by adding this to config:
```
vmap S <Plug>VSurround
```
This lines maps S in visual mode to call VSurround command of the surround plugin.
