### ISSUE TITLE
Support ignorecase and smartcase

### ISSUE THREAD

**Issue by MunsterPlop** [Mishkun/ideavim-sneak#17]
In vim-sneak, you can set `g:sneak#use_ic_scs`.

From `:help sneak`:
```
g:sneak#use_ic_scs = 0

    0: Always case-sensitive

    1: Case sensitivity is determined by 'ignorecase' and 'smartcase'.
```

Ideavim already supports `set ignorecase smartcase`, so this setting would take that into account.

**Comment by xiaoouwang** [comment]
up ! I need this feature too, really useful !

**Comment by MunsterPlop** [comment]
I came up with a working solution, I'll make a PR soon.
