### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by AlexPl292** [Mishkun/ideavim-sneak#2]
The license section says that this plugin is licensed under GPL-2.0: https://github.com/Mishkun/ideavim-sneak#license
But the license file itself refers to GPL-3.0: https://github.com/Mishkun/ideavim-sneak/blob/master/LICENSE.txt
The "license" link on the plugins page refers to GPL-3.0 as well.

**Comment by Mishkun** [comment]
Thanks for noticing, updated to GPLv3 everywhere
