### ISSUE TITLE
improve the repeating action (; and ,) implementation

### ISSUE THREAD

**Issue by jannes** [Mishkun/ideavim-sneak#8]

**Comment by jannes** [comment]
The repeating actions for 'f' and 't' are in the MotionGroup class like you already said.
~~But somehow other repeating motions like 'w' and 'b' are also implemented, just haven't figured out how yet.~~
(edit: incorrect statement)

**Comment by Mishkun** [comment]
@jannes I just tested with vanilla IdeaVim configuration and cannot make `;` and `,` to work with `w` and `b`. Are you sure they are repeatable?

**Comment by jannes** [comment]
hey, I just tested this again and you are right, they are not repeated.
it was probably just repeating an earlier f move and i didn't look close enough.
furthermore, this also not the vim behavior, only f,t,F,T are repeated with ;.

so i think for now your implementation of forwarding to the f,t,F,T handlers
is the best possible for a separate plugin. 
and when we merge it into the main repo, we could potentially change the MotionGroup
class to use the same mechanism as f,t,F,T (if that is deemed ok by the maintainer).
